

package com.sample;


import com.sample.Server


rule "Check Server Configuration"
  @activationGroup("sample")
  @silent(true)
  salience 99
  when
  $server : Server((!fired.contains("sample")) && (processors <= 2 || memory<=1024 || diskspace <= 2048))
  then
  $server.setValid(false);
  System.out.println( $server.getName() + " configuration1 does not meet requirements!");
end


rule "Check Server Configuration2"
  activation-group "sample"
  salience 98
  when
  $server : Server( processors < 2 || memory<=3024 || diskspace <= 3048)
  then
  $server.getFired().add(drools.getRule().getActivationGroup());
  update($server);
  //$server.updateFired($server,drools.getRule().getActivationGroup())
  $server.setValid(false);
  System.out.println( $server.getName() + " configuration2 does not meet requirements!");
end


rule "Check Server Configuration3"
  @activationGroup("sample")
  salience 97
  when
    $server : Server((!fired.contains("sample")) && (processors < 2 || memory<=3024 || diskspace <= 3048))
  then
  $server.setValid(false);
  System.out.println($server.getName() + " configuration3 does not meet requirements!");
end